/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HelloQuaiInterface extends Interface {
  getFunction(nameOrSignature: "getMessage" | "setMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMessage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setMessage", values: [string]): string;

  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMessage", data: BytesLike): Result;
}

export namespace MessageChangedEvent {
  export type InputTuple = [sender: AddressLike, newMessage: string];
  export type OutputTuple = [sender: string, newMessage: string];
  export interface OutputObject {
    sender: string;
    newMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HelloQuai extends BaseContract {
  connect(runner?: ContractRunner | null): HelloQuai;
  waitForDeployment(): Promise<this>;

  interface: HelloQuaiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMessage: TypedContractMethod<[], [string], "view">;

  setMessage: TypedContractMethod<[newMessage: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMessage"
  ): TypedContractMethod<[newMessage: string], [void], "nonpayable">;

  getEvent(
    key: "MessageChanged"
  ): TypedContractEvent<
    MessageChangedEvent.InputTuple,
    MessageChangedEvent.OutputTuple,
    MessageChangedEvent.OutputObject
  >;

  filters: {
    "MessageChanged(address,string)": TypedContractEvent<
      MessageChangedEvent.InputTuple,
      MessageChangedEvent.OutputTuple,
      MessageChangedEvent.OutputObject
    >;
    MessageChanged: TypedContractEvent<
      MessageChangedEvent.InputTuple,
      MessageChangedEvent.OutputTuple,
      MessageChangedEvent.OutputObject
    >;
  };
}
