/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QNSController } from "./QNSController";
export type { QNSRegistry } from "./QNSRegistry";
export type { SocialPosts } from "./SocialPosts";
