/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { QNSController__factory } from "./QNSController__factory";
export { QNSRegistry__factory } from "./QNSRegistry__factory";
